CREATE DATABASE DATA_SOURCE_DB
GO

USE DATA_SOURCE_DB
GO

CREATE TABLE CITY (
    CITY_ID INT PRIMARY KEY,
    CITY_NAME NVARCHAR(100) NOT NULL,
    COUNTRY NVARCHAR(100) NOT NULL,
    LAT FLOAT NOT NULL,
    LON FLOAT NOT NULL
)

CREATE TABLE TIME (
    TIME_ID INT INDENTITY(1,1) PRIMARY KEY,
    HOUR INT NOT NULL,
    MINUTE INT NOT NULL,
    SECOND INT NOT NULL,
    TIME_BUCKET NVARCHAR(32) NOT NULL
)