spark.master spark://spark-master:7077

spark.jars /opt/spark/custom_jars/*


spark.sql.extensions io.delta.sql.DeltaSparkSessionExtension
spark.sql.catalog.spark_catalog org.apache.spark.sql.delta.catalog.DeltaCatalog

spark.sql.warehouse.dir s3a://elt-weather-bucket/warehouse

spark.driver.memory 512m
spark.executor.memory 512m
spark.executor.cores 1
spark.executor.instances 1
