FROM apache/airflow:2.10.4-python3.11

USER root
WORKDIR /opt/airflow
USER airflow
ENV PYTHONPATH=/opt/airflow
COPY requirements.txt /requirements.txt

# Cài đặt với constraints file của Airflow để tránh xung đột
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir \
    -r /requirements.txt